AtmClean/urls.py
from django.contrib import admin
from django.urls import path, re_path, include
from AtmClean import views


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("ticketFinder.urls")),
    re_path(r'^atmPostService/', include("atmPostService.urls")),
    re_path(r'generatePDF/$', views.GeneratePDF.as_view()),
]

ticketFinder/urls.py
from django.contrib import admin
from django.urls import path, re_path
from ticketFinder import views
from AtmClean import views as vw

app_name = 'ticketFinder'
    
urlpatterns = [    
    path('', views.index, name = 'index'),
    re_path(r'options/$',views.options, name = 'options'),
    re_path(r'ecode/$', views.ecode, name = 'ecode'),
    path('cuestionario/', views.cuestionario, name = 'cuestionario'),
    re_path(r'POST_buscar/$', views.POST_cuestionario, name = 'POST_cuestionario'),
    re_path(r'charts/$', views.charts, name='charts'),
    re_path(r'POST_ecode2tran/$', views.POST_ecode2tran, name='ecode2tran'),
    re_path(r'cuestionario/generatePDF/$', vw.GeneratePDF.as_view(), name = 'genPDFs'),
    
]

templates/base.html
<!DOCTYPE html>
{% load staticfiles %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="icon" href="{% static "favicon.png" %}" type="image" sizes="16x16">
    <link rel="stylesheet" href="{% static "styles.css" %}">  
    <script
    src="{% static "jquery/jquery.js" %}"
    crossorigin="anonymous"></script>
    {% block head_block %}
    {% endblock %} 
</head>
<body>
    <div class="navbar_principal">                                      
        <div class="nav_element"><a href="https://www.bancomer.com/"><img src="{% static "logo.svg" %}" alt="BVVA Bancomer logo"></a></div>
        <!-- <div class="nav_element" style="padding-right:125px;"><img src="icon.svg" style="width: 25px;" alt="Menu icon"></div> -->
    </div>
    <!-- Navbar -->
    {% block body_block %}
    {% endblock %}
    <!-- Web page body -->

    <div class="footer">
        <div class="footer-container">
                <div class="footer-row1">      
                        <a href="https://www.bbva.com/es/mx/"><img src="{% static "logo-footer.svg" %}" alt="BVVA Logo"></a>
                        <div class="footer-row1-e1">
                            <div class="footer-row1-e1-im">
                                <img src="{% static "stripes-header-after.png" %}" width="100%;">
                            </div>  
                        </div>
                </div>
                <div class="footer-row2">
                    <a href="https://openspace.bbva.com/aviso-legal/" class="footer-row2-links">Aviso legal</a>
                    <a href="https://openspace.bbva.com/politica-de-cookies/" class="footer-row2-links" style="margin-right: 30px;">Cookies</a>
                    <a href="https://openspace.bbva.com/proteccion-de-datos/" class="footer-row2-links">Datos personales</a>
                    <a href="https://openspace.bbva.com/seguridad/" class="footer-row2-links">Seguridad</a>
                    <a href="https://www.bbva.com/es/mx/" class="footer-row2-links">Web corporativa BBVA</a>
                </div>
        </div>
    </div>
    <!-- Footer -->

     <!-- Con esta línea de código estoy importando la librería de JQuery -->
    <script type="text/javascript" src="{% static "action.js" %}"></script>
</body>
</html>

templates/charts.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
<html lang="en">
    {% block head_block%}
    <link rel="stylesheet" href="{% static "morris.css" %}">
    <title>Gráfica Lineal</title>
    {% endblock %}
    {% block body_block%}
    <div>
        <div id="myfirstchart" style="height: 450px;"></div>
    </div>
    <!-- Esta es la gráfica, dentro del style la puedes comunicar como quieras, a fuerza debe tener
    esas librerías de arriba y de abajo importadas y tener el archivo morris.css y morris.min.js
    La gráfica se crea en el archivo action.js -->

    <script src="http://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js"></script>
    <script src="http://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js"></script>
    <script src="{% static "morris.min.js" %}"></script>
    {% endblock%}

templates/cuestionario.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
    {% block head_block %}
    <title>Cuestionario</title>
    {% endblock %}

    {% block body_block %}
    <div style="display: flex;flex-direction: column;width: 88.15%;height: 550px;padding-left: 80px;padding-right: 80px;">
        <div style="width: 100%;height: 170px;margin-bottom: 50px;">
            <p class="text" style="font-size:30px;font-weight: 900;color: black;padding-top: 50px;">
            Contesta el siguiente cuestionario
            </p>
            <div style="background-color: #2dcccd; height: 10px; width: 50px;margin-top:10px;"></div>
            <p class="text" style="font-size:20px;">
            No todos los campos son obligatorios, pero mientras más información nos pueda 
            proporcionar, más le podremos asegurar que encontraremos el comprobante que requiere.
            </p>
        </div>
            {% csrf_token   %}
            <form id="pedrito">
                <div style="width: 100%;height: 110px;padding-left: 1px;padding-right: 1px;display: flex;flex-wrap: nowrap;flex-direction: row;justify-content: space-around;">
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Tipo de transaccion: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <select id="tipo" class="searcher">
                                <option value="empty">Seleccionar</option>
                                <option value="0">Deposito cuenta</option>
                                <option value="1">Pago de Servicio</option>
                                <option value="2">Pago tarjeta de crédito</option>
                                <option value="3">Pago de crédito o préstamo</option>
                                <option value="4">Consultar saldos y movimientos</option>
                                <option value="5">Prestamo disponible</option>
                                <option value="6">Tiempo aire</option>
                                <option value="7">Retiro</option>
                            </select> 
                        </div>
                    </div>
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Fecha en la que se hizo la transacción: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <div style="display:flex;justify-content:center;">
                                <input id="fecha" type="date" class="searcher">
                            </div>
                        </div>
                    </div>
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Rango de hora en la que se hizo la transacción: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <select id="hora" class="searcher">
                                    <option value="empty">Seleccionar</option>
                                <option value="00-02">12:00 am-2:00 am</option>
                                <option value="02-04">2:00 am-4:00 am</option>
                                <option value="04-06">4:00 am-6:00 am</option>
                                <option value="06-08">6:00 am-8:00 am</option>
                                <option value="08-10">8:00 am-10:00 am</option>
                                <option value="10-12">10:00 am-12:00 pm</option>
                                <option value="12-14">12:00 pm-2:00 pm</option>
                                <option value="14-16">2:00 pm-4:00 pm</option>
                                <option value="16-18">4:00 pm-6:00 pm</option>
                                <option value="18-20">6:00 pm-8:00 pm</option>
                                <option value="20-22">8:00 pm-10:00 pm</option>
                                <option value="22-24">10:00 pm-12:00 am</option>
                            </select>
                        </div>
                    </div>
                </div>
                <div style="width: 100%;height: 110px;padding-left: 1px;padding-right: 1px;display: flex;flex-wrap: nowrap;flex-direction: row;justify-content: space-around;">
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Ubicación del ATM: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <div>
                                <select id="estado" class="searcher">
                                        <option value="empty">Seleccionar</option>
                                    <option value="Aguascalientes">Aguascalientes</option>
                                    <option value="Baja California">Baja California</option>
                                    <option value="Baja California Sur">Baja California Sur</option>
                                    <option value="Campeche">Campeche</option>
                                    <option value="Coahuila de Zaragoza">Coahuila de Zaragoza</option>
                                    <option value="Colima">Colima</option>
                                    <option value="Chiapas">Chiapas</option>
                                    <option value="Chihuahua">Chihuahua</option>
                                    <option value="Distrito Federal">Distrito Federal</option>
                                    <option value="Durango">Durango</option>
                                    <option value="Guanajuato">Guanajuato</option>
                                    <option value="Guerrero">Guerrero</option>
                                    <option value="Hidalgo">Hidalgo</option>
                                    <option value="Jalisco">Jalisco</option>
                                    <option value="Estado de México">Estado de México</option>
                                    <option value="Michoacán">Michoacán</option>
                                    <option value="Morelos">Morelos</option>
                                    <option value="Nayarit">Nayarit</option>
                                    <option value="Nuevo León">Nuevo León</option>
                                    <option value="Oaxaca">Oaxaca</option>
                                    <option value="Puebla">Puebla</option>
                                    <option value="Querétaro">Querétaro</option>
                                    <option value="Quintana Roo">Quintana Roo</option>
                                    <option value="San Luis Potosí">San Luis Potosí</option>
                                    <option value="Sinaloa">Sinaloa</option>
                                    <option value="Sonora">Sonora</option>
                                    <option value="Tabasco">Tabasco</option>
                                    <option value="Tamaulipas">Tamaulipas</option>
                                    <option value="Tlaxcala">Tlaxcala</option>
                                    <option value="Veracruz">Veracruz</option>
                                    <option value="Yucatán">Yucatán</option>
                                    <option value="Zacatecas">Zacatecas</option>
                                    </select>
                            </div>
                        </div>
                    </div>
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Ubicación del ATM: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <div>
                                <input id="municipio" type="text" class="searcher" placeholder="Municipio/Delegación" value="empty">
                            </div>
                        </div>
                    </div>
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        
                    </div>
                </div>
                <div style="width: 100%;height: 110px;padding-left: 1px;padding-right: 1px;display: flex;flex-wrap: nowrap;flex-direction: row;justify-content: space-around;">
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Banco de la cuenta: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <select id="banco" class="searcher">
                                <option value="Bancomer">Bancomer</option>
                                <option value="Banamex">Banamex</option>
                                <option value="Santander">Santander</option>
                                <option value="Banorte">Banorte</option>
                                <option value="Banxico">Banxico</option>
                            </select>
                        </div>
                    </div>
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                        <p class="text" style="color:black;">Últimos 4 dígitos de la cuenta: </p>
                        <div class="search" style="margin:0px;width: 300px;">
                            <div>
                                <input id="u4" type="number" class="searcher" placeholder="Ej: 9864">
                            </div>
                        </div>
                    </div>
                    <div style="width:367px;height: 60px;display: flex;flex-direction: column;">
                    </div>
                </div>
            </div>
            <div style="display:flex;justify-content:center;align-items:center;height: 100px;margin-bottom: 30px;">
                <button id="mandar_cuestionario" type="submit" class="button" style="font-size: 20px;" value="Enviar Cuestionario">Enviar</button>
            </div>
        </form>
        <!-- Web page body -->
        {% endblock%}

templates/eCode.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
    {% block head_block %}
    <title>eCode</title>
    {% endblock %}

    {% block body_block %}
    <div class="background_questionary">
        <div class="welcome_text" style="width:46.3%;height: 100px;padding-right: 0px;">
            <p style="margin-bottom:20px;">Listo</p>
            <p class="text" style="font-size:20px;">
                Introduce tu código eCode que te apareció en la pantalla del cajero automático cuando realizaste tu transacción, 
                y gracias por ayudarnos a mantener al planeta tan hermoso como ya lo es. 
            </p>
        </div>
        <div class="background_options" style="width:55%;height: 350px;">
            <div id="submit_container">
                <div id="search">
                    <div>
                        <input id="ecode" type="text" class="searcher" placeholder="Introduce tu eCode">
                    </div>
                </div>
                <input id="enviar" type="submit" class="submit_button" name="send_eCode" value="Enviar">
            </div>
        </div> 
    </div>
    <!-- Web page body -->
    <script src="{% static "ecode.js" %}" ></script>
    {% endblock%}

templates/index.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
    
    {% block head_block %}
    <title>Bancomer</title>
    {% endblock %}



        {% block body_block %}
    <div class="background_index">
        <div class="div-container">
            <div id="leaf-image">
                        <img src="{% static "leaf.jpg" %}" style="width: 68px;" alt="Leaf logo">
            </div>
            <div id="message">
                <h1 class="title">Envío de comprobante</h1>
                <div style="background-color: #2dcccd; height: 10px; width: 50px;margin-bottom: 30px;margin-top:10px;"></div>
                <p class="text">
                    En Bancomer nos preocupamos por la problematica actual del daño 
                    al medio ambiente, debido a ello, ideamos una campaña donde creamos 
                    un código llamado eCode, esto se planteó en el Hackathon BBVA Bancomer 2018.
                    Decir que este programa se hizo por la chaviza en el hackaton, introducir 
                    código que me regresó el ATM llamado e-Code.
                </p>
            </div>
            <div id="button-container">
                <a href="{% url "ticketFinder:options" %}"><button class="button" ><p>SOLICITA TU COMPROBANTE</p></button></a>
            </div>
        </div>
    </div>
    <!-- Web page body -->
    {% endblock %}

    

templates/options.html
<!DOCTYPE html>
{% extends "base.html" %}
{% load staticfiles %}
    {% block head_block %}
    <title>Plazo de 7 días.</title>
    {% endblock %}
    
    {% block body_block %}
    <div class="welcome_text">
        <p style="margin-bottom:20px;">¡Bienvenido!</p>
        <p class="text" style="font-size:20px;">
            ¿Han pasado más de 7 días desde que hiciste tu transacción?
        </p>
    </div>
    <div class="background_options">
        <!-- <div style="width:100%;height:50%;display:flex;justify-content:center;align-items:center;">
            <div id="search">
                <div style="width:530px; padding-left:16px">
                    <input type="text" class="searcher" placeholder="Introduce tu e-Code">
                </div>
            </div>
        </div> -->
        <div id="button_container">
            <a href="{% url "ticketFinder:cuestionario" %}"><button class="button" style="font-size:18px;width:270px;">Sí, han pasado más de 7 días.</button></a>
            <a href="{% url "ticketFinder:ecode" %}"><button class="button" style="font-size:18px;width:270px;">No, han pasado menos de 7 días.</button></a>
        </div>
    </div>
    <!-- Web page body -->
    {% endblock %}

templates/pdf.html
<!DOCTYPE html>
{% load staticfiles %}
<html>
    
<center>
<p style="text-align: center;">&nbsp;</p>
<tbody>
<tr>
<td style="width: 575px;">
<p style="text-align: center;">&nbsp;</p>
<p style="text-align: center;"><span style="color: #00ccff;">
<blockquote>
<img src="{% static "logo.png" %}" width="300" height="300">
<h2><span style="color: #00ccff;">{{ tipo }}</span></h2>
<h3><span style="color: #00ccff;">Comprobante Digita</span> - Cajero Autom&aacute;tico</h3>
<p>&nbsp;</p>
<table style="border-collapse: collapse;" width="1000"> 
<tbody>
<tr>
<td style="text-align: right; width: 255px;">
<h4>No. Cajero:</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;{{ id_atm }}</h4>
</td>
</tr>
<tr>
<td style="text-align: right; width: 255px;">
<h4>Ubicaci&oacute;n del Cajero:</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;{{ banco }}</h4>
</td>
</tr>
<tr>
<td style="text-align: right; width: 255px;">
<h4>Cuenta de Retiro:</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;{{ cuenta }}</h4>
</td>
</tr>
<tr>
<td style="text-align: right; width: 255px;">
<h4>Beneficieario:&nbsp;</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;{{ beneficiario }}</h4>
</td>
</tr>
<tr>
<td style="text-align: right; width: 255px;">
<h4>Importe:&nbsp;</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;<span style="color: #00ccff;">{{ importe }}</span></h4>
</td>
</tr>
<tr>
<td style="text-align: right; width: 255px;">
<h4>Fecha de Operaci&oacute;n:&nbsp;</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;{{ fecha }}</h4>
</td>
</tr>
<tr>
<td style="text-align: right; width: 255px;">
<h4>Folio de Operaci&oacute;n:&nbsp;</h4>
</td>
<td style="width: 224px;">
<h4>&nbsp;{{ folio }}</h4>
</td>
</tr>
</tbody>
</table>
</IMG>
</blockquote>
<h4 style="text-align: center;"><span style="color: #000000; background-color: #99ccff;">En caso de no reconocer esta operaci&oacute;n, comunicate al 01 800 22 62 633.&nbsp;Este comprobante digital constituye una notificaci&oacute;n de los t&eacute;rminos en que realiz&oacute; la operaci&oacute;n , el &uacute;nico comprobante oficial es el que emite BBVA Bancomer.</span></h4>
<p style="text-align: center;"><span style="color: #000080;">&nbsp;</span></p>
<p style="text-align: center;">Alertas Bancomer te protege, te mantiene informado de la actividad de las cuentas, conoce m&aacute;s en <a href="http://www.bancomer.mx">www.bancomer.mx.</a></p>
</td>
</tr>
</tbody>
<p style="text-align: left;">&nbsp;</p>
<p>&nbsp;</p>
</center>
</html>